version: '3'

services:
  backend:
    build: ./backend
    restart: always
  frontend:
    depends_on:
      - backend
    build: ./frontend
    restart: always

  minio:
    image: minio/minio
    volumes:
      - minio-data:/data
    ports:
      - "9090:9090"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server /data --console-address ":9090"

  mongodb:
    image: mongo
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

  nginx:
    image: nginx
    ports:
      - "3000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend

volumes:
  mongo-data:
  minio-data:
