[auth]
# auth-url = "https://datafoundation.iiit.ac.in/api" # uncomment this to use the production auth server
secret-key = "supertopsecret"
algorithm = "HS256"
access-token-expire-minutes = 60

[mongo]
# host = "mongodb" # use this for production
host = "localhost"
port = 27017
db = "dfs-drive"

[minio]
# host = "minio" # use this for production
host = "localhost:9000"
username = "minio"
password = "minio123"
bucket = "data-drive"